'use client';

import React, { useState, useRef } from 'react';
import { Download, Copy, Check, Edit3, X, Maximize2, ChevronLeft, ChevronRight, Sparkles, Loader2 } from 'lucide-react';
import { Button } from "@/components/ui/button";
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface DeckData {
    companyName: string;
    tagline: string;
    problem: string;
    solution: string;
    market: string;
    traction: string;
    team: string;
    ask: string;
    competition: string;
    businessModel: string;
    goToMarket: string;
}

interface DeckPreviewProps {
    data: DeckData;
    template: 'sequoia' | 'yc' | 'modern';
    onReset: () => void;
}

interface SlideProps {
    title: string;
    content: string;
    number: number;
    template: string;
    isEditing: boolean;
    onEdit: () => void;
    onSave: (content: string) => void;
    onCancel: () => void;
}

const Slide: React.FC<SlideProps> = ({
    title,
    content,
    number,
    template,
    isEditing,
    onEdit,
    onSave,
    onCancel
}) => {
    const [editContent, setEditContent] = useState(content);

    // Template Styles
    const styles = {
        sequoia: "bg-white border-gray-200 font-serif",
        yc: "bg-gray-50 border-transparent font-sans",
        modern: "bg-gradient-to-br from-gray-900 to-gray-800 text-white border-gray-700"
    };

    const titleStyles = {
        sequoia: "text-gray-900 font-serif",
        yc: "text-black font-bold uppercase tracking-tight",
        modern: "text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400 font-bold"
    };

    const contentStyles = {
        sequoia: "text-gray-600",
        yc: "text-gray-800 font-medium",
        modern: "text-gray-300 font-light"
    };

    const handleSave = () => {
        onSave(editContent);
    };

    return (
        <div
            className={`aspect-video rounded-xl border p-8 flex flex-col shadow-sm hover:shadow-md transition-all relative overflow-hidden group slide-card ${styles[template as keyof typeof styles]}`}
        >
            <div className="absolute top-0 right-0 px-4 py-2 text-xs font-mono opacity-30">
                {number < 10 ? `0${number}` : number}
            </div>

            {/* Edit button - visible on hover */}
            {!isEditing && (
                <button
                    onClick={onEdit}
                    className="absolute top-2 right-10 opacity-0 group-hover:opacity-100 transition-opacity p-2 rounded-lg bg-black/10 hover:bg-black/20"
                >
                    <Edit3 className="w-4 h-4" />
                </button>
            )}

            <h3 className={`text-2xl mb-6 ${titleStyles[template as keyof typeof titleStyles]}`}>{title}</h3>

            {isEditing ? (
                <div className="flex-grow flex flex-col">
                    <textarea
                        value={editContent}
                        onChange={(e) => setEditContent(e.target.value)}
                        className="flex-grow w-full p-3 rounded-lg border border-gray-300 resize-none text-sm text-gray-800 bg-white"
                        autoFocus
                    />
                    <div className="flex justify-end gap-2 mt-3">
                        <button
                            onClick={onCancel}
                            className="px-3 py-1.5 text-sm rounded-lg border border-gray-300 hover:bg-gray-100 flex items-center gap-1"
                        >
                            <X className="w-3 h-3" />
                            Cancel
                        </button>
                        <button
                            onClick={handleSave}
                            className="px-3 py-1.5 text-sm rounded-lg bg-blue-600 text-white hover:bg-blue-700 flex items-center gap-1"
                        >
                            <Check className="w-3 h-3" />
                            Save
                        </button>
                    </div>
                </div>
            ) : (
                <div className={`flex-grow whitespace-pre-wrap leading-relaxed text-sm ${contentStyles[template as keyof typeof contentStyles]}`}>
                    {content || "No content provided."}
                </div>
            )}

            <div className="mt-4 pt-4 border-t border-white/10 flex justify-between items-center opacity-0 group-hover:opacity-100 transition-opacity">
                <span className="text-xs opacity-50">Generated by Buzzedison</span>
            </div>
        </div>
    );
};

// Presentation Mode Component
const PresentationMode: React.FC<{
    slides: Array<{ title: string; content: string }>;
    template: string;
    onClose: () => void;
}> = ({ slides, template, onClose }) => {
    const [currentSlide, setCurrentSlide] = useState(0);

    const styles = {
        sequoia: "bg-white text-gray-900",
        yc: "bg-gray-50 text-black",
        modern: "bg-gradient-to-br from-gray-900 to-gray-800 text-white"
    };

    const titleStyles = {
        sequoia: "font-serif",
        yc: "font-bold uppercase tracking-tight",
        modern: "text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400"
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'ArrowRight' || e.key === ' ') {
            setCurrentSlide(prev => Math.min(prev + 1, slides.length - 1));
        } else if (e.key === 'ArrowLeft') {
            setCurrentSlide(prev => Math.max(prev - 1, 0));
        } else if (e.key === 'Escape') {
            onClose();
        }
    };

    return (
        <div
            className={`fixed inset-0 z-50 flex items-center justify-center ${styles[template as keyof typeof styles]}`}
            onKeyDown={handleKeyDown}
            tabIndex={0}
            autoFocus
        >
            {/* Close button */}
            <button
                onClick={onClose}
                className="absolute top-6 right-6 p-3 rounded-full bg-black/20 hover:bg-black/40 transition-colors z-10"
            >
                <X className="w-6 h-6" />
            </button>

            {/* Navigation */}
            <button
                onClick={() => setCurrentSlide(prev => Math.max(prev - 1, 0))}
                disabled={currentSlide === 0}
                className="absolute left-6 p-4 rounded-full bg-black/20 hover:bg-black/40 transition-colors disabled:opacity-30"
            >
                <ChevronLeft className="w-8 h-8" />
            </button>

            <button
                onClick={() => setCurrentSlide(prev => Math.min(prev + 1, slides.length - 1))}
                disabled={currentSlide === slides.length - 1}
                className="absolute right-6 p-4 rounded-full bg-black/20 hover:bg-black/40 transition-colors disabled:opacity-30"
            >
                <ChevronRight className="w-8 h-8" />
            </button>

            {/* Slide Content */}
            <div className="max-w-4xl w-full px-16 text-center">
                <div className="mb-4 text-sm opacity-50">
                    {currentSlide + 1} / {slides.length}
                </div>
                <h1 className={`text-5xl md:text-7xl font-bold mb-8 ${titleStyles[template as keyof typeof titleStyles]}`}>
                    {slides[currentSlide].title}
                </h1>
                <p className="text-xl md:text-2xl leading-relaxed opacity-80 whitespace-pre-wrap">
                    {slides[currentSlide].content}
                </p>
            </div>

            {/* Slide indicators */}
            <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex gap-2">
                {slides.map((_, idx) => (
                    <button
                        key={idx}
                        onClick={() => setCurrentSlide(idx)}
                        className={`w-2 h-2 rounded-full transition-all ${idx === currentSlide ? 'bg-white w-8' : 'bg-white/30 hover:bg-white/50'
                            }`}
                    />
                ))}
            </div>
        </div>
    );
};

const DeckPreview: React.FC<DeckPreviewProps> = ({ data, template, onReset }) => {
    const [copied, setCopied] = useState(false);
    const [editingSlide, setEditingSlide] = useState<number | null>(null);
    const [slideData, setSlideData] = useState(data);
    const [exporting, setExporting] = useState(false);
    const [showPresentation, setShowPresentation] = useState(false);
    const [enhancingAll, setEnhancingAll] = useState(false);
    const slidesRef = useRef<HTMLDivElement>(null);

    const slides = [
        { title: slideData.companyName || "Company Name", content: slideData.tagline, key: 'tagline' },
        { title: "The Problem", content: slideData.problem, key: 'problem' },
        { title: "The Solution", content: slideData.solution, key: 'solution' },
        { title: "Market Opportunity", content: slideData.market, key: 'market' },
        { title: "Business Model", content: slideData.businessModel, key: 'businessModel' },
        { title: "Competition", content: slideData.competition, key: 'competition' },
        { title: "Go-to-Market", content: slideData.goToMarket, key: 'goToMarket' },
        { title: "Traction & Milestones", content: slideData.traction, key: 'traction' },
        { title: "Team", content: slideData.team, key: 'team' },
        { title: "The Ask", content: slideData.ask, key: 'ask' },
    ];

    const handleCopy = () => {
        const text = JSON.stringify(slideData, null, 2);
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSlideEdit = (index: number) => {
        setEditingSlide(index);
    };

    const handleSlideSave = (index: number, content: string) => {
        const key = slides[index].key as keyof DeckData;
        setSlideData(prev => ({ ...prev, [key]: content }));
        setEditingSlide(null);
    };

    const handleExportPDF = async () => {
        if (!slidesRef.current) return;

        setExporting(true);

        try {
            const pdf = new jsPDF({
                orientation: 'landscape',
                unit: 'px',
                format: [1280, 720]
            });

            const slideElements = slidesRef.current.querySelectorAll('.slide-card');

            for (let i = 0; i < slideElements.length; i++) {
                const slideEl = slideElements[i] as HTMLElement;

                // Create canvas from slide
                const canvas = await html2canvas(slideEl, {
                    scale: 2,
                    useCORS: true,
                    backgroundColor: template === 'modern' ? '#1f2937' : '#ffffff',
                });

                const imgData = canvas.toDataURL('image/png');

                if (i > 0) {
                    pdf.addPage();
                }

                // Add image to PDF - fit to page
                pdf.addImage(imgData, 'PNG', 0, 0, 1280, 720);
            }

            pdf.save(`${slideData.companyName || 'pitch-deck'}.pdf`);
        } catch (error) {
            console.error('PDF export failed:', error);
            alert('Failed to export PDF. Please try again.');
        } finally {
            setExporting(false);
        }
    };

    const handleEnhanceAll = async () => {
        setEnhancingAll(true);

        const fieldsToEnhance = ['tagline', 'problem', 'solution', 'market', 'businessModel', 'competition', 'goToMarket', 'traction', 'team', 'ask'];

        for (const field of fieldsToEnhance) {
            const content = slideData[field as keyof DeckData];
            if (!content) continue;

            try {
                const response = await fetch('/api/gemini', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        action: 'enhance',
                        content,
                        fieldName: field
                    })
                });

                if (response.ok) {
                    const data = await response.json();
                    setSlideData(prev => ({ ...prev, [field]: data.result }));
                }
            } catch (error) {
                console.error(`Failed to enhance ${field}:`, error);
            }
        }

        setEnhancingAll(false);
    };

    return (
        <>
            <div className="w-full max-w-7xl mx-auto animate-fade-in">
                <div className="text-center mb-12">
                    <div className="inline-flex items-center px-3 py-1 rounded-full bg-green-100 text-green-700 mb-4 text-sm font-medium">
                        <Check className="w-4 h-4 mr-2" />
                        Deck Generated Successfully
                    </div>
                    <h2 className="text-4xl font-bold text-gray-900 mb-4 font-serif">Your Pitch Deck Outline</h2>
                    <p className="text-gray-500 max-w-2xl mx-auto mb-2">
                        Template Style: <span className="font-bold capitalize text-gray-900">{template === 'yc' ? 'Y Combinator' : template}</span>
                    </p>
                    <p className="text-sm text-gray-400">
                        Click on any slide to edit • Press the present button for full-screen mode
                    </p>
                </div>

                <div ref={slidesRef} className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
                    {slides.map((slide, idx) => (
                        <Slide
                            key={idx}
                            number={idx + 1}
                            title={slide.title}
                            content={slide.content}
                            template={template}
                            isEditing={editingSlide === idx}
                            onEdit={() => handleSlideEdit(idx)}
                            onSave={(content) => handleSlideSave(idx, content)}
                            onCancel={() => setEditingSlide(null)}
                        />
                    ))}
                </div>

                <div className="flex flex-wrap justify-center gap-4">
                    <Button variant="outline" onClick={onReset} className="h-12 px-6">
                        Start Over
                    </Button>

                    <Button
                        variant="outline"
                        onClick={() => setShowPresentation(true)}
                        className="h-12 px-6"
                    >
                        <Maximize2 className="w-4 h-4 mr-2" />
                        Present
                    </Button>

                    <Button onClick={handleCopy} className="h-12 px-6 bg-gray-900 text-white hover:bg-gray-800">
                        {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                        {copied ? 'Copied to Clipboard' : 'Copy All Content'}
                    </Button>

                    <Button
                        onClick={handleEnhanceAll}
                        disabled={enhancingAll}
                        className="h-12 px-6 bg-gradient-to-r from-purple-500 to-blue-500 text-white hover:from-purple-600 hover:to-blue-600"
                    >
                        {enhancingAll ? (
                            <>
                                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                Enhancing...
                            </>
                        ) : (
                            <>
                                <Sparkles className="w-4 h-4 mr-2" />
                                Enhance All with AI
                            </>
                        )}
                    </Button>

                    <Button
                        onClick={handleExportPDF}
                        disabled={exporting}
                        className="h-12 px-6 bg-blue-600 text-white hover:bg-blue-700 shadow-lg shadow-blue-200"
                    >
                        {exporting ? (
                            <>
                                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                Generating PDF...
                            </>
                        ) : (
                            <>
                                <Download className="w-4 h-4 mr-2" />
                                Export as PDF
                            </>
                        )}
                    </Button>
                </div>
            </div>

            {/* Presentation Mode */}
            {showPresentation && (
                <PresentationMode
                    slides={slides}
                    template={template}
                    onClose={() => setShowPresentation(false)}
                />
            )}
        </>
    );
};

export default DeckPreview;
