
// app/layout.tsx
import React from 'react'; // Import React
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavbarNew from './components/MyNav';
import Footer from './components/Footer';
import GoogleAnalytics from "@/components/GoogleAnalytics";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Buzzedison',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode; // Explicitly type the children prop
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS && (
          <GoogleAnalytics ga_id={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
        )}
        <NavbarNew/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
