import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import GoogleAnalytics from "@/components/GoogleAnalytics"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Buzzedison',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS ? (
            <GoogleAnalytics ga_id={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
          ) : null}
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
